### ISSUE TITLE
iOS 7 Support

### ISSUE THREAD

**Issue by adamkaplan** [mickeyreiss/TypeJSON#1]
Mind setting the Pod version to iOS 7.0? It's currently at 8.1, which prevents using this in most production apps. I don't see any reason to have such a heavy restriction. In fact, you could probably support iOS 5.0 without any code changes.

With that said, iOS 7 is the most common base version these days.

**Comment by mickeyreiss** [comment]
I originally chose iOS 8.1 due to the fact that it was the only runtime I had tested in. 

I'm happy to accept pull requests that add iOS 7.0 support, especially if they are tested and you'd like to ship an iOS 7.0 app with this library.

**Comment by adamkaplan** [comment]
That's the response I would send... ok

:-P

**Comment by adamkaplan** [comment]
All tests pass!

**Comment by mickeyreiss** [comment]
Thanks for contributing. Expect a v0.0.3 release imminently.
