### ISSUE TITLE
Date support

### ISSUE THREAD

**Issue by adamkaplan** [mickeyreiss/TypeJSON#3]
JSON dates are supported by `NSJSONSerialization`. They hydrate into instances of `NSDate`.

**Comment by mickeyreiss** [comment]
As I wrote in the README, I am interested in surfacing the constraints and simplicity of the [JSON spec](http://json.org/). 

Since dates are not defined in JSON, I don't think `asDate` belongs in `TypeJSON`.

**Comment by adamkaplan** [comment]
I see. It's your call. Given the ubiquity of ISO-8601 dates in JSON and the "just works" nature of that format in browsers and the standard parsers like Jackson, etc, it seems to have little risk compared to annoyance of `NSDateFormatter`.

You can close this.

**Comment by mickeyreiss** [comment]
For now at least, this library is going to be a bit philosophical when it comes to JSON.

Feel free to write some code if you'd like to discuss this more. :octocat:
