### ISSUE TITLE
Generic object initializer

### ISSUE THREAD

**Issue by adamkaplan** [mickeyreiss/TypeJSON#4]
Please either expose `-initWithValue:` or provide a `+fromObject:` static method. The reason is that once a client uses asArray or asDictionary they will have left the safe bouncy castle provided by TypeJSON. Since nearly all useful JSON is not totally flat, this is problematic.

There is the method of running the collection through NSData, and then feeding it into `+fromData:`, but that is a bit absurd considering that support for direct wrapping would be 1 LOC.

**Comment by mickeyreiss** [comment]
Thanks for bringing this up. I'm glad you're exercising the library and identifying its limitations.

The intention behind exposing `-objectForKeyedSubscript:` and `-objectAtIndexedSubscript:` was to allow for this type of traversal in deeply nested JSON structures.

For example, for a JSON strcuture like this:

``` json
{
  "root": {
    "key": "value",
  }
}
```

you should access `"value"` like this:

``` objectivec
TypeJSON *json = [TypeJSON fromData:RAW_JSON];
NSLog(json["root"]["key"].asString);
// => @"value"
```

In general, `-asArray` is only intended to be used when an `NSArray` of `id`s is sufficient (and the same for `-asDictionary`/`NSDictionary`). If Objective-C supported generics, I would consider `-asArray` returning an `NSArray<TypeJSON>`—even without the type-safety, I would consider changing this aspect of the library.

Can you provide a case where this is not sufficient?

**Comment by adamkaplan** [comment]
So the problem is that my parsing code is distributed through the JSON/PONSO model hierarchy. So, each JSON "object" roughly maps to one JSON model with a parser. This means that in practice I have to keep wrapping the NSArray/NSDictionary returned via keyed subscripting instances in new TypeJSON wrappers in each model instance.

Anyway, the real ideal case is for `asArray` or `asDictionary` to return something like Jackson's `JsonNode`, or something like `NSArray<TypeJson>`. I spent some serious time today seeing if it was possible to implement `NSFastEnumeration` in a way that intercepts & wraps the values that the underlying collection returns. It's not possible without some serious re-tooling due to lack of ownership on the wrapped values. Was a fun experiment anyway :)

**Comment by mickeyreiss** [comment]
> wrapping the NSArray/NSDictionary returned via keyed subscripting instances in new TypeJSON 

The subscript methods in TypeJSON [return a `TypeJSON *`](https://github.com/mickeyreiss/TypeJSON/blob/e3fb30c6b7d9455260a79bb48890155f58cedfe1/TypeJSON.m#L57-L68), not an `NSDictionary` or `NSArray`. Am I missing something?

**Comment by adamkaplan** [comment]
Oh, no you didn't. I was in a rush to get to dinner and neglected to realize that :-/

What actually sent me down this rabbit hole was the pursuit of fast enumeration. I'm a diehard fan of NSFastEnumeration, it's mutation protections, concurrency and  efficiencies over for(). That's why I mentioned it above... though I don't have a solution.

**Comment by mickeyreiss** [comment]
Yes, It would be possible to add conformance to `NSFastEnumeration`.
